### PR TITLE
Fix CORS, add GH actions to publish helm repo, fix npm audit issues

### PR DESCRIPTION
**Pull request by kirgene**
* fix CORS
* add GH actions to publish helm repo
* fix npm audit issues by directly requiring some transitive dependencies in `package.json`- these may be able to be removed in future

### CODE REVIEW

**Review by bushjames — APPROVED** [review]

**Comment by partiallyordered** [comment]
What's driving all the new packages in `package.json`? I can't see them used in any of the file changes here.

**Comment by kirgene** [comment]
Currently the `npm-force-resolutions` package is used to fix `npm audit` issues by patching sub dependencies in `package-lock.json` during `npm install` phase. The problem with this approach is that when changing sub dependencies that have new dependencies added there is no way to install them during `npm install` (chicken-and-egg problem).
So to overcome this problem, those sub-sub dependencies should be explicitly added to package.json.

**Comment by partiallyordered** [comment]
Is there a way to keep track of that? One suggestion: IIRC the GH PR title/description goes into a squash merge, so the information could go in the GH PR description, and you could squash merge. So that future readers have a chance of tracking down why those packages are there (`git blame`). What do you think?

**Comment by kirgene** [comment]
Good suggestion. I've added the changes to the description of the PR.
For the future PRs I think we can separate `npm audit` fixes and other changes in different PRs.

**Review by partiallyordered — APPROVED** [review]

**Pull request merged**
